apiVersion: v1
kind: Service
metadata:
        name: {{ .Release.Name }}-mysql
spec:
        selector:
                app: mysql
        ports:
                - protocol: TCP
                  port: {{ .Values.mysql.port }}
                  targetPort: {{ .Values.mysql.port }}

